arb-dir: lib/l10n
output-dir: lib/l10n/demo_localization
template-arb-file: intl_en.arb
output-localization-file: demo_kit_client_localizations.dart
output-class: DemoKitClientLocalizations
header-file: header.txt
synthetic-package: false
untranslated-messages-file: untranslated.txt

